language: node_js
node_js:
  - 'node'
env:
  global:
    - EXTENSION_ID=pogpjdbfdfnmlegpbhdmlebognmbamko
deploy:
  provider: script
  skip_cleanup: true
  script: npm run build && npm run update-version && npm run release
  on:
    branch: master
